### ISSUE TITLE
访问不了

### ISSUE THREAD

**Issue by youppos** [ellermister/mybili#4]
当我访问http://10.10.10.11:5151/
报500
Server Error
![image](https://github.com/user-attachments/assets/1e59cc08-d780-4652-b08e-35983713036c)

**Comment by ellermister** [comment]
看看容器内的日志 /app/storage/logs/laravel.log

**Comment by youppos** [comment]
```shell
#11 /app/vendor/laravel/horizon/src/Console/HorizonCommand.php(36): Laravel\\Horizon\\Repositories\\RedisMasterSupervisorRepository->find('235f6bf8629a-Fc...')
#12 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\HorizonCommand->handle(Object(Laravel\\Horizon\\Repositories\\RedisMasterSupervisorRepository))
#13 /app/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#14 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#15 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#16 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#17 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\\Container\\Container->call(Array)
#18 /app/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#19 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#20 /app/vendor/symfony/console/Application.php(1047): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /app/vendor/symfony/console/Application.php(316): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\HorizonCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 /app/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(197): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1203): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 /app/artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#26 {main}

[previous exception] [object] (ErrorException(code: 0): Redis::connect(): php_network_getaddresses: getaddrinfo for redis failed: Name does not resolve at /app/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:159)
[stacktrace]
#0 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Redis::connect(...', '/app/vendor/lar...', 159)
#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(2, 'Redis::connect(...', '/app/vendor/lar...', 159)
#2 /app/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(159): Redis->connect('redis', '6379', 0.0, NULL, 0, 0.0)
#3 /app/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(88): Illuminate\\Redis\\Connectors\\PhpRedisConnector->establishConnection(Object(Redis), Array)
#4 /app/vendor/laravel/framework/src/Illuminate/Support/helpers.php(380): Illuminate\\Redis\\Connectors\\PhpRedisConnector->Illuminate\\Redis\\Connectors\\{closure}(Object(Redis))
#5 /app/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(79): tap(Object(Redis), Object(Closure))
#6 /app/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(33): Illuminate\\Redis\\Connectors\\PhpRedisConnector->createClient(Array)
#7 /app/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(38): Illuminate\\Redis\\Connectors\\PhpRedisConnector->Illuminate\\Redis\\Connectors\\{closure}()
#8 /app/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(110): Illuminate\\Redis\\Connectors\\PhpRedisConnector->connect(Array, Array)
#9 /app/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(91): Illuminate\\Redis\\RedisManager->resolve('horizon')
#10 /app/vendor/laravel/horizon/src/Repositories/RedisMasterSupervisorRepository.php(161): Illuminate\\Redis\\RedisManager->connection('horizon')
#11 /app/vendor/laravel/horizon/src/Repositories/RedisMasterSupervisorRepository.php(73): Laravel\\Horizon\\Repositories\\RedisMasterSupervisorRepository->connection()
#12 /app/vendor/laravel/horizon/src/Repositories/RedisMasterSupervisorRepository.php(62): Laravel\\Horizon\\Repositories\\RedisMasterSupervisorRepository->get(Array)
#13 /app/vendor/laravel/horizon/src/Console/HorizonCommand.php(36): Laravel\\Horizon\\Repositories\\RedisMasterSupervisorRepository->find('235f6bf8629a-Fc...')
#14 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\HorizonCommand->handle(Object(Laravel\\Horizon\\Repositories\\RedisMasterSupervisorRepository))
#15 /app/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#17 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#18 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#19 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\\Container\\Container->call(Array)
#20 /app/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#21 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#22 /app/vendor/symfony/console/Application.php(1047): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 /app/vendor/symfony/console/Application.php(316): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\HorizonCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 /app/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(197): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1203): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 /app/artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#28 {main}

```

**Comment by ellermister** [comment]
你没有部署 redis，参考 docker-compose.yml

**Comment by summ9919** [comment]
![微信截图_20240920170803](https://github.com/user-attachments/assets/30e4ee8d-24e7-4bbe-a86e-7f79aa306f1e)
qi
![微信截图_20240920170816](https://github.com/user-attachments/assets/b5188fb6-3ef7-4b37-acd3-b7c6ef947c9d)
你好，请问为何redis不能启动，我自己弄的测试的却能启动，是我哪里设置不对吗？
![Uploading 微信截图_20240920171034.png…]()

**Comment by summ9919** [comment]
谢谢你的解答，我刚刚成功启动了，不过又有新的日志提示了
![微信截图_20240920172715](https://github.com/user-attachments/assets/460e7c68-d9b6-4da0-a144-f4740dafb2c4)
b
并且我还是访问提示500，我真是错误百出，万分感谢。
![微信截图_20240920172944](https://github.com/user-attachments/assets/c736073d-3d77-4a00-8f12-47fc891fd058)

**Comment by ellermister** [comment]
redis的 warning先忽略，你查看laravel日志，在mybili容器内部：/app/storage/logs/laravel.log

**Comment by summ9919** [comment]
[2024-09-20 08:38:09] production.ERROR: php_network_getaddresses: getaddrinfo for redis failed: Try again {"exception":"[object] (RedisException(code: 0): php_network_getaddresse
s: getaddrinfo for redis failed: Try again at /app/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:159)
[stacktrace]
#0 /app/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(159): Redis->connect('redis', '6379', 0.0, NULL, 0, 0.0)
#1 /app/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(88): Illuminate\\Redis\\Connectors\\PhpRedisConnector->establishConnection(Object(Redis), A
rray)
#2 /app/vendor/laravel/framework/src/Illuminate/Support/helpers.php(380): Illuminate\\Redis\\Connectors\\PhpRedisConnector->Illuminate\\Redis\\Connectors\\{closure}(Object(Redis)
)
#3 /app/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(79): tap(Object(Redis), Object(Closure))
#4 /app/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(33): Illuminate\\Redis\\Connectors\\PhpRedisConnector->createClient(Array)
#5 /app/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(38): Illuminate\\Redis\\Connectors\\PhpRedisConnector->Illuminate\\Redis\\Connectors\\{clos
ure}()
#6 /app/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(110): Illuminate\\Redis\\Connectors\\PhpRedisConnector->connect(Array, Array)
#7 /app/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(91): Illuminate\\Redis\\RedisManager->resolve('horizon')
#8 /app/vendor/laravel/horizon/src/Repositories/RedisMasterSupervisorRepository.php(161): Illuminate\\Redis\\RedisManager->connection('horizon')
#9 /app/vendor/laravel/horizon/src/Repositories/RedisMasterSupervisorRepository.php(73): Laravel\\Horizon\\Repositories\\RedisMasterSupervisorRepository->connection()
#10 /app/vendor/laravel/horizon/src/Repositories/RedisMasterSupervisorRepository.php(62): Laravel\\Horizon\\Repositories\\RedisMasterSupervisorRepository->get(Array)
#11 /app/vendor/laravel/horizon/src/Console/HorizonCommand.php(36): Laravel\\Horizon\\Repositories\\RedisMasterSupervisorRepository->find('bf0cd695d7db-TE...')
#12 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\HorizonCommand->handle(Object(Laravel\\Horizon\\Repositories\\RedisMast
erSupervisorRepository))
#13 /app/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#14 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#15 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), A
rray, Object(Closure))
#16 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array,
 NULL)
#17 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\\Container\\Container->call(Array)
#18 /app/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\
\OutputStyle))
/app/storage/logs/laravel.log

**Comment by ellermister** [comment]
你的.env 完整复制一份 https://github.com/ellermister/mybili/blob/main/.env.example 并只修改其中的 redis 配置和 APP_KEY，再重启试试

**Comment by summ9919** [comment]
非常感谢，我按照你的方法搞定了。
